### ISSUE TITLE
UPGRADE ????

### ISSUE THREAD

**Issue by PauloBoaventura** [rafaelstz/magento-correios-rastreio#1]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

S.O = Centos7 - Plesk
Php = 5.6 / 7.0

**Comment by rafaelstz** [comment]
Para falar a verdade eu não me lembrava desse módulo que fiz, vou fazer um upgrade nele, mas não recomendo utilizar sem testar. Ele não é um módulo de calculo dos Correios, é um módulo para rastreio de encomendas.

**Comment by PauloBoaventura** [comment]
Olá @rafaelstz 
Obrigado pela disponibilidade de fazer um upgrade no modulo.

Sabe me dizer se pode colocar algo relacionado ao calculo de frete e envio deste para a finalização do pedido?

Agradeço qualquer ajuda!

**Comment by rafaelstz** [comment]
Para implementar o cálculo dos Correios na sua loja eu recomendo esse módulo abaixo.
https://github.com/pedro-teixeira/correios

**Comment by PauloBoaventura** [comment]
Olá @rafaelstz este modulo esta desatualizado, assim como muitos outros... 
Por isso estou buscado outras alternativas satisfatórias... 

Obrigado pela ajuda!
